language: java
jdk: oraclejdk8
disk: trusty
deploy: 
  provider: heroku
  api_key:
    secure: "pQSOFwkxeyd2CGZEalgMufdEZ+dkdDw3/FS3MtrSid5KPoK8RCdaU6/o++Ydz4V1mmY5QU/YlHdHdAJ3OY+pP1l4O5rER8jvrVPcR6xUOGcabkOpRGGC03T8Nej9yd4r0AMJiIN9HlJBGhbGiAf0E2TUmmCUUblqrIW9WVbrRm1Km/pcLcGTgeiIVjjPxtuBvfgeu+rjzC6hDZhEM2ke7P1f9uadKaLBwpQu8GerzUYTLKuQ7BZUThH9CSBK0dMrPAG3yw5N5FuHJNsMwaaEohjMGtAkyvP3wFte5G+IwDC16Y4TrQafDL3EcBCNa2g6r0H9Kep15U2GvnkkZgGyDuIquFBN4J0/zh4+fpQoOl55+AyWArXCNPuCcnVAQlv267Np7G+SXolEVro4Xx82wswElDohfaSZxz0HzKmRD459LSlBNxkuJnCHDuPx0Ba4v57+hPoFX9/I5ETawbZdrWvBpa2bePJPe0Cn6hu6wDKvrLBnQ3YV2NkS8eyPlKnWcUwQzLtt+jrZ9I4LG3aN+ZBAQlRnH7BVIboCiyugwcuGBpaS5IQLRJiOhx7XV29ZqdSlKRDaQRGNVBsmmj2WBGO+0e53lP31rpm6+RdosqKOaTJzhG2b5LbLKvAg3Wx1eoCy3In7CD7DZahHayH5cyERtg2ASvMoei9wT/DT7HU="
  App: damasorecordatorios
